NDefines_Graphics.NAirGfx.MAX_MISSILE_BOMBING_SCENARIOS = 1
NDefines_Graphics.NAirGfx.MAX_BOMBING_SCENARIOS = 1
NDefines_Graphics.NAirGfx.MAX_PATROL_SCENARIOS = 1
NDefines_Graphics.NAirGfx.MAX_DOGFIGHTS_SCENARIOS = 1
NDefines_Graphics.NAirGfx.MAX_TRANSPORT_SCENARIOS = 1
NDefines_Graphics.NAirGfx.AIRPLANES_ANIMATION_GLOBAL_SPEED_PER_GAMESPEED = {0.3, 0.3, 0.3, 0.3, 0.3, 0.3}
NDefines_Graphics.NAirGfx.AIRPLANES_SMOOTH_INTERPOLATION_MOVE = 0.02
NDefines_Graphics.NAirGfx.AIRPLANES_SMOOTH_INTERPOLATION_TURN = 0.02

NDefines_Graphics.NMapMode.MAP_MODE_TERRAIN_TRANSPARENCY = 0.8